### PR TITLE
Remove unecessary single quotation

### PR DESCRIPTION
**Pull request by ashWhiteHat**
I found a type so I fixed.
Please confirm.
Thank you.

### CODE REVIEW

**Comment by ashWhiteHat** [comment]
@kirillt 
Is this still being maintained?

**Comment by kirillt** [comment]
@NoCtrlZ not really, but thank you for this fix.

**Comment by kirillt** [comment]
@NoCtrlZ I don't have permissions to apply merge requests here, you can ask @folsen or submit this PR to my fork: https://github.com/kirillt/substrate-cli-tools/

**Comment by ashWhiteHat** [comment]
@kirillt 
I got it, thank you!

@folsen 
I fixed the typo.
Could you confirm my change?
Thank you.

**Pull request closed without merging**
